apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-srri
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-srri
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-srri
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-srri
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-srri
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ppzz-tenant/rhtap-demo-app/hacbs-test-project-srri@sha256:d8af3d6caabccfb7e1d30c2a36e4e8fb9f5e705a35bbfa6f559a58c76291fc84
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
